### ISSUE TITLE
drag event not captured when over bubble node

### ISSUE THREAD

**Issue by alon** [Rhizi/rhizi#117]
bubble node needs to be made event invisible.

**Comment by Garbash** [comment]
From how I understand the description this issue is obsolete @alon concur?

**Comment by alon** [comment]
description suggests you try to drag something when over the bubble. if
you cannot bug is still applicable.

**Comment by Garbash** [comment]
As any existing nodes moves away from the bubble . The only drag event possible is dragging one of the preview nodes, which doesn't make much sense as an issue because panning the map already achieves this.
