### ISSUE TITLE
While editing a node/link - text shifts left to cover circle (chrome only)

### ISSUE THREAD

**Issue by Garbash** [Rhizi/rhizi#237]
Instruction: entire node name should appear, without overlap, never shifting left

Before clicking and opening the edit node box:
![screen shot 2014-12-23 at 18 51 43](https://cloud.githubusercontent.com/assets/1841864/5540480/c5786076-8ad4-11e4-873a-a0f4d68d7060.png)
When edit node box is open:
![screen shot 2014-12-23 at 18 51 49](https://cloud.githubusercontent.com/assets/1841864/5540481/c85aeafc-8ad4-11e4-8275-1d6d9b12a6e0.png)
Person clicking on the node name should be able to see the entire text at once.

**Comment by Garbash** [comment]
Closed by unknown old commit

**Comment by alon** [comment]
Do you know any commit that isn't old? :P

**Comment by Garbash** [comment]
Ok rephrasing - didn't manage to find the commit # for the fix
