### ISSUE TITLE
firefox with vimperator: enter in textanalysis doesn't work

### ISSUE THREAD

**Issue by alon** [Rhizi/rhizi#347]
clicking plus button is a workaround

Or found.

**Comment by Garbash** [comment]
@alon is this still a thing?

**Comment by alon** [comment]
I think oz opened this, you can see the bug owner.

**Comment by Garbash** [comment]
It says here you opened this issue

**Comment by alon** [comment]
ok, but for oz. you can close it as "won't fix"

**Comment by Garbash** [comment]
ok
