### ISSUE TITLE
Use ";" for creating multiple nodes

### ISSUE THREAD

**Issue by Garbash** [Rhizi/rhizi#528]
So:
Dor;Alon;Amir
Creates three orphan nodes.

**Comment by jibe-b** [comment]
I suggest to enable the RDF/Turtle syntax:

> subject predicate subject .
subject predicate1 object 1 ; predicate2 object2 .
subject predicate object1 , object2.

Hence, multiple nodes would be truncated triples, like:

> subject1 . subject2 .

**Comment by Garbash** [comment]
Closed because the ";" is confusing and also doesn't address any real user issue at the moment. Oh hello @jibe-b what brings you here?

**Comment by jibe-b** [comment]
Hi @Garbash, I am interested by Rhizi as a way to edit RDF graph visually. RDF is my approach, but I am open to other projects.
