### ISSUE TITLE
Error when using :, ", ?,., or ' chars in input bar.

### ISSUE THREAD

**Issue by Garbash** [Rhizi/rhizi#594]
If I type in input bar ":" or "test hello:" or "hello  is:  fine":
I get the following error:
ajax error: status: 'error', error-msg: cypher parse error: rgx match failure: rgx: ^`(?P<value>[\w\d_\-\s]+(\*\d*\.\.\d*)?)`(?P<suffix>.*)$, input: "`Is:` {link_attr}]->(dst) with r, src, dst order by r.id return {id: r.id, __src_id: src.id, __dst_id: dst.id, __type: type(r)}"on_error_wrapper @ rz_api_backend.js:25jQuery.Callbacks.fire @ jquery.js:3119jQuery.Callbacks.self.fireWith @ jquery.js:3231done @ jquery.js:9277jQuery.ajaxTransport.send.callback @ jquery.js:9685

**Comment by alon** [comment]
אוקיי, קל לתיקון.

**Comment by Garbash** [comment]
Note that I've add " char as one that also cause error

**Comment by alon** [comment]
Fixed by 2f0be9ac314efc927ba7dd108908306622193957.

Note that the double quote char is accepted but dropped silently. Opened issue 623 to track that.

**Comment by Garbash** [comment]
Another critical char causes the bug: "."

**Comment by Garbash** [comment]
It's in fact a different bug, as the nodes are actually created, just not displayed after submit.
Posting this as a separate issue
