### ISSUE TITLE
filter menu: use domain type classes

### ISSUE THREAD

**Issue by alon** [Rhizi/rhizi#606]
i.e. put the class name used for domain type on the row, so if the filter shows:

A, B, C

then A will use class_a, B class_b, and C class_c

**Comment by Garbash** [comment]
This was left here a while ago so clarifying:
The filter menu can act as a map legend. We just need to add the colors of the types as a dot next to the type name:
Quick sketch:
![screen shot 2015-12-15 at 7 37 12 pm](https://cloud.githubusercontent.com/assets/1841864/11831494/92b9ba60-a363-11e5-84b4-f4dc3187bf54.png)
Where the nodes appear next to all filter items, not just the first.
Anyway @clemsos please take the liberty to make it nicer looking :)

**Comment by Garbash** [comment]
Abi's feedback - add a small rectangle in the far right of the list.

**Comment by Garbash** [comment]
Closed via https://github.com/Rhizi/rhizi/commit/6352560e3782810c52cb8dc671b0b939341be6e3
