### ISSUE TITLE
While deploying local, db_driver.py raises exception "failed to open transaction: ' + e.message"

### ISSUE THREAD

**Issue by jibe-b** [Rhizi/rhizi#647]
Hi, I try to deploy Rhizi locally, but it fails. I am not used to the configuration of neo4j (users, etc).

Config:
rhizi-0.0.1-20150427-014900
neo4j-community-2.3.1

running: 
> ant -f ./build.ant deploy-local

ok

and modifed etc/rhizi-server.conf

> sed '%user_db_path =% s%deploy-local/%%' etc/rhizi-server.conf

then:

> cd deploy-local && python bin/rz_server.py --config-dir=etc

Log

>2015-11-16 17:00:27,848 [INFO] rhizi user DB located, path: ./etc/user_db.db
2015-11-16 17:00:27,858 [INFO] rhizi user DB initialized: path: ./etc/user_db.db, user-count: 0
2015-11-16 17:00:27,867 [INFO] rhizi rz_kernel: on-line
2015-11-16 17:00:27,882 [ERROR] rhizi op: DBO_nop: tx-id: None
Traceback (most recent call last):
  File "/opt/rhizi-0.0.1-20150427-014900/src/server/db_controller.py", line 39, in exec_op
    self.db_driver.begin_tx(op)
  File "/opt/rhizi-0.0.1-20150427-014900/src/server/db_driver.py", line 57, in begin_tx
    raise Exception('failed to open transaction: ' + e.message)

Inside src/server/db_driver.py, the exception raised is commented as follow:

> [!] neo4j seems picky about receiving an additional empty statement list

Your help will be welcome!

**Comment by alon** [comment]
Since some recent neo4j version the default is authentication required, but rhizi doesn't support that. So to turn off authentication (assuming this is the cause) set in neo4j-server.properties:

  dbms.security.auth_enabled=false

**Comment by jibe-b** [comment]
thanks! but not finished

still in deploy-local/

> failed to initialize server: 'Config' object has no attribute 'log_path'
Traceback (most recent call last):
  File "bin/rz_server.py", line 435, in <module>
    log = init_log(cfg)
  File "bin/rz_server.py", line 246, in init_log
    log_handler_f = logging.FileHandler(cfg.log_path)
AttributeError: 'Config' object has no attribute 'log_path'

Do I add a value myself? (at this stage, I don't think about log files)

**Comment by jibe-b** [comment]
etc/rhizi-server.conf is empty!

I start again.

**Comment by alon** [comment]
see run-local.sh - it copies the example config file for you if you did not do it yourself. If you prefer not to use it just follow it:
cp res/etc/rhizi-server.conf.example res/etc/rhizi-server.conf

**Comment by jibe-b** [comment]
Thanks again. Now my question is how to add a user. Signup page tries to send an email to the adress I give and returns:

> 2015-11-16 22:09:08,868 [ERROR] rhizi user sign-up: failed to send validation email
Traceback (most recent call last):
  File "/opt/rhizi-0.0.1-20150427-014900/src/server/rz_user.py", line 435, in rest__user_signup
    activation_link = send_user_activation_link__email(us_req)
  File "/opt/rhizi-0.0.1-20150427-014900/src/server/rz_user.py", line 485, in send_user_activation_link__email
    activation_link = 'http://%s/signup?v_tok=%s' % (current_app.rz_config.SERVER_NAME,
AttributeError: 'Config' object has no attribute 'SERVER_NAME'
127.0.0.1 - - [2015-11-16 22:09:08] "POST /signup HTTP/1.1" 500 227 0.005875

In etc/rhizi-server.conf, SERVER_NAME has no value (I tried imap.orange.fr port 993 on which I have an account but it's not enough). Is it needed to go through the signup process or can I add a user's credentials by another way (I am the only user of my machine)?

I will try again tomorrow to go through the installation of Rhizi. Thanks for helping me installing it.
