### ISSUE TITLE
While deploying local, email server needed. How to bypass ?

### ISSUE THREAD

**Issue by jibe-b** [Rhizi/rhizi#649]
Still installing Rhizi with neo4j-2.2.1.

The signup page needs to send an email before creating a user. Can I bypass this step and add a user directly in the database?

log:
> 2015-11-21 10:34:30,466 [ERROR] rhizi user sign-up: failed to send validation email
Traceback (most recent call last):
  File "/opt/rhizi-0.0.1-20150427-014900/src/server/rz_user.py", line 435, in rest__user_signup
    activation_link = send_user_activation_link__email(us_req)
  File "/opt/rhizi-0.0.1-20150427-014900/src/server/rz_user.py", line 485, in send_user_activation_link__email
    activation_link = 'http://%s/signup?v_tok=%s' % (current_app.rz_config.SERVER_NAME,
AttributeError: 'Config' object has no attribute 'SERVER_NAME'
127.0.0.1 - - [2015-11-21 10:34:30] "POST /signup HTTP/1.1" 500 227 0.038656

Otherwise, how do I change these entries in etc/rhizi-server.conf? I use the orange.fr webmail, (incoming: imap.orange.fr:993 ; outgoing: smtp.orange.fr 465)

>\# Flask Configuration
>\#    - [!] SERVER_NAME: if adding ':port', this should match listen_port
>\#SERVER_NAME = :8080
SECRET_KEY = notverysecretbutpeppyyaya
>\# use with HTTPS: SESSION_COOKIE_SECURE = True
>\# Mail
mta_host = 127.0.0.1
mta_port = 25
mail_default_sender = rhizi@localhost
feedback_recipient = feedback@localhost
>\# Security
access_control = True
user_db_path = ./etc/user_db.db
acl__singup__email_domain =

Best regards,

**Comment by alon** [comment]
You can disable access control if you don't need users via the config file.
You can use bin/rz-user-tool as well. The installation process is not yet streamlined, but the tool can take the user db file as a parameter (run it with --help to see how). To run it from the repository use:
PYTHONPATH=. bin/rz-user-tool --help

**Comment by jibe-b** [comment]
Thanks! Now I can play with Rhizi.

May I ask you  @alon what type of feedback you would like to have on Rhizi?
I will tinker with Rhizi and with neo4j in the next weeks, with one idea in mind: how to use it to author (RDF) graphs visually. If you are interested, I can list the different features that would be needed (and the ones that already exist, in particular neo4j plugins).

**Comment by alon** [comment]
There is someone doing a discussion graph based on rhizi, although I forget his name. Feel free to open an issue / issues about specific things. This would be perfect for a mailing list discussion, if we bothered to set one up :/

**Comment by ozFri** [comment]
By discussion graph you mean my project?
It is based on RDF
בתאריך 22 בנוב 2015 09:54,‏ "alon" <notifications@github.com> כתב:

**Comment by alon** [comment]
yep, sorry for forgetting your name Oz.

**Comment by jibe-b** [comment]
Can you tell me where I can find your project, @ozFri, so that I take a look at it?

**Comment by ozFri** [comment]
@jibe-b
The repository is here
https://github.com/ozFri/rhizi/

**Comment by jibe-b** [comment]
@ozFri commit history does not inform me much about the introduction of RDF into Rhizi. Did you write your plans somewhere? or would give me a little bit more details?

Best

**Comment by ozFri** [comment]
We can talk on skype about this, my address is oz.fraier, I will be
available in a hour or two
בתאריך 4 בדצמ 2015 11:44,‏ "jibe-b" <notifications@github.com> כתב:

**Comment by ozFri** [comment]
@jibe-b ^

**Comment by alon** [comment]
run one. Easiest way to run a do nothing server that I know of: python -m smtpd -n -c DebuggingServer localhost:25
need to run that as root, or use a >1024 numbered port and change rhizi config file accordingly.

**Comment by alon** [comment]
oops, saw the mail and answered again according to the title, ignoring the thread. Please disregard this and the previous comments.

**Comment by jibe-b** [comment]
otherwise: install postfix, and the account activation link is given on the terminal.
