### ISSUE TITLE
Edge arrows blocking node labels

### ISSUE THREAD

**Issue by Garbash** [Rhizi/rhizi#653]
This is a newly introduced bug.
Expected behavior:
Edge arrows should only be seen on hover or when a node has been selected.
![screen shot 2015-12-03 at 10 31 57 pm](https://cloud.githubusercontent.com/assets/1841864/11583378/d8b778f4-9a0d-11e5-8ac2-379314746dcf.png)

**Comment by clemsos** [comment]
7d3fb0b solved this by painting arrows in gray
![selection_030](https://cloud.githubusercontent.com/assets/743246/11598364/bcea6cbc-9ac1-11e5-9522-522b39b0577f.png)

**Comment by clemsos** [comment]
7d3fb0b improves this fix with opacity.

**Comment by alon** [comment]
do you mind if I leave this open since the fill:'AAA' is just a workaround? the wanted behaviour is not to show the arrows for unselected nodes.

**Comment by alon** [comment]
hmm, nevermind, I'm a slow reader, just saw #655
