### ISSUE TITLE
Sign-in fields should have autocompete

### ISSUE THREAD

**Issue by Garbash** [Rhizi/rhizi#656]
When a user signs-in, the field should allow auto-complete in a similar way any form field in browsers do. E.g. autocomplete your email address or name field

**Comment by clemsos** [comment]
This feature is named "autofill" (autocomplete is more for search boxes). Problem comes from the fact that the HTML is wrong : the signup / signin forms are all contains in DIV tags when they should be FORM tags.

**Comment by clemsos** [comment]
not sure how the template deployment works though to fix this
