### ISSUE TITLE
Custom layout: Lose position when using filter and doc change and layout change

### ISSUE THREAD

**Issue by Garbash** [Rhizi/rhizi#675]
(1) In custom mode, fix position on two nodes
(2) Filter nodes
(3) Switch to force layout
(4) open a different document
(5) Return to original document
(6) Switch to custom 
(7) Unfilter nodes

**Comment by alon** [comment]
what happens after a refresh (reload of page)?

**Comment by Garbash** [comment]
Seems like original positions are restored - but losing position is still unexpected behaviour that might lead user to move the node position around. 
Probably connected to simpler issue #676
