### ISSUE TITLE
Add piwik analytics code in every web page

### ISSUE THREAD

**Issue by Garbash** [Rhizi/rhizi#678]
Instructions from Piwik: (Open source analytics tool)

"Copy this code and paste it just before the closing </body> tag on each page of your website. Or, just send this code and instructions to your developer."

<script type="text/javascript">
    var _paq = _paq || [];
    _paq.push(['trackPageView']);
    _paq.push(['enableLinkTracking']);
    (function() {
    var u="//rhizi.piwikpro.com//";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', 1]);
    var d=document, g=d.createElement('script'), 
    s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; 
    g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
    })();
    </script>
<noscript><p>
  <img src="//rhizi.piwikpro.com/piwik.php?idsite=1" 
  style="border:0;" alt="" /></p>
  </noscript>

**Comment by clemsos** [comment]
@Garbash where is Piwik hosted ? do we have a single Piwik ID per instance ? Should we add the Piwik ID in the config ?

**Comment by Garbash** [comment]
Piwik is hosted on their server.
http://piwik.org/hosting/
We have a general Piwik id, and there's a plug-on that should enable us to
parse between the different instances.
https://piwik.pro/plugins/meta-sites/

I don't think we should configure anything in addition, but not completely
sure. Will dig in once the initial code is pasted.
BTW - the code exists in the issue, just click on the edit button on the
issue description to see it.

On Fri, Dec 11, 2015 at 1:54 PM, Clément Renaud <notifications@github.com>
wrote:

> @Garbash <https://github.com/Garbash> where is Piwik hosted ? do we have
> a single Piwik ID per instance ? Should we add the Piwik ID in the config ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Rhizi/rhizi/issues/678#issuecomment-164059503>.
>



-- 
+1-(415)-527-8124

**Comment by alon** [comment]
of course use the config for the id, and do not commit it by any means. Dor - otherwise you end up letting anyone contaminate your analytics / access them.

**Comment by Garbash** [comment]
You are the expert. I can only point to general documentation they have such as:
http://developer.piwik.org/api-reference/tracking-javascript

If we later want to add additional tracking etc'

**Comment by clemsos** [comment]
Piwik support added in d780a9d . should change piwik_id and piwiki_url in the config file,  then it will add the tracking code on the main page.

@Garbash what do you want to track exactly ? There is actually many options here http://developer.piwik.org/guides/tracking-javascript-guide

**Comment by alon** [comment]
closed by ecbf6adac1168583c5ba2388869aa22259b6060b
