### ISSUE TITLE
Data schema: edge labels?

### ISSUE THREAD

**Issue by jibe-b** [Rhizi/rhizi#718]
In the UI, edges have a visible label.

Neo4j accepts only one property per edge, in Rhizi it's _id_.

I would like to have them as a result of a Cypher query. How are they stored?

**Comment by alon** [comment]
Hi jibe-b,

 Why don't you use the neo4j web ui (defaults to port 7474) to look? I don't recall off the top of my head, but it isn't that convoluted.

Alon

**Comment by jibe-b** [comment]
@alon Indeed I looked up and as edges have only one property, their must have been a choice on how to store edge labels.

What is the naming convention (at least in comments): are edges labels called _name_? _label_?

I look up in the code right now.

**Comment by jibe-b** [comment]
I see in [/test_util__rz_doc.py](https://github.com/Rhizi/rhizi/blob/c3b9043a4a25968b015fb66870e5a01d11f30655/rhizi/tests/test_util__rz_doc.py) how edge id may be generated. Is there maybe a test python script producing a mock graph with labels?

**Comment by jibe-b** [comment]
I think I got it: label is stored as category of the edge.

> 'create (s)-[:%s {l_attr_0:toInt(%d * rand())}]->(d)' % (self.r_label, lim_r)]

source: [neo4j_test_util.py](https://github.com/Rhizi/rhizi/blob/c3b9043a4a25968b015fb66870e5a01d11f30655/rhizi/tests/neo4j_test_util.py)

Right?

**Comment by jibe-b** [comment]
I got it, I was wrong about the Cypher function to use.

Answer:

nodes have a _label_ and relationships have a _type_.

So in Cypher:

> MATCH ()-[r]->() RETURN distinct type(r)

**Comment by jibe-b** [comment]
Thanks @alon.

I am trying to make Rhizi and my RDF workflow interoperable. I'll pull if I have something valuable for Rhizi at the end (possibly export to RDF/turtle).
