### ISSUE TITLE
Installation issue: build.ant

### ISSUE THREAD

**Issue by jibe-b** [Rhizi/rhizi#719]
Trying to install latest rhizi,
running ./run-local.sh

[Edit: bower was removed from my machine in fact :/]

**Comment by jibe-b** [comment]
2. There is an rsync issue:

rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.0]

Build failed [...] build.ant:138: The following error occurred while executing this line

**Comment by jibe-b** [comment]
3. when I copy the content of client to deploy-local/static,

In the javascript console of firefox, I get: 

> The stylesheet http://localhost:8080/static/css/style.css was not loaded because its MIME type, “text/html”, is not “text/css”.index
The stylesheet http://localhost:8080/static/css/feedback.css was not loaded because its MIME type, “text/html”, is not “text/css”.index

**Comment by jibe-b** [comment]
I will greatly welcome help, rhizi is quite unique in the field of visual authoring of property graphs and if I can use it on daily basis I will probably take my part in maintenance.

**Comment by jibe-b** [comment]
It now works.

**Comment by alon** [comment]
Hi jibe-e

It took me a while to get to this. I'm glad that you managed to get it working meanwhile. Is there anything that you still want? you can contact me personally, I'm also on the irc at irc.oftc.net #rhizi .

Alon
